apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: closed-junglefowl-nodejs 
  janus-idp.io/tekton: closed-junglefowl-nodejs
  backstage.io/kubernetes-id: closed-junglefowl-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: closed-junglefowl-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  