apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: closed-junglefowl-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: closed-junglefowl-nodejs 
  name: closed-junglefowl-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: closed-junglefowl-nodejs 
